### POST request to create a new patient
POST localhost:4000/patients
Content-Type: application/json

{
  "name": "Someone Someone sending kafka",
  "email": "sendanalytics@test.com",
  "address": "123 main street22",
  "dateOfBirth": "1995-09-10",
  "registeredDate": "2024-11-28"
}