package sideeffects;

import org.junit.jupiter.api.Test;
import webrequests.BaseIntegrationTest;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.*;

public class BillingSideEffectTest extends BaseIntegrationTest {

    @Test
    public void shouldEnsureBillingAccountIsCreatedViaGrpc() {
        String token = authenticateAndGetToken();
        String patientEmail = "billing-test-" + System.currentTimeMillis() + "@test.com";

        String payload = String.format("""
        {
          "name": "Billing User",
          "email": "%s",
          "address": "gRPC Lane",
          "dateOfBirth": "1985-10-10",
          "registeredDate": "2026-03-27"
        }
    """, patientEmail);

        // 1. Create the patient and EXTRACT the ID from the response body
        // Rest-Assured makes this easy with .extract().path("id")
        String extractedPatientId = given()
                .header("Authorization", "Bearer " + token)
                .contentType("application/json")
                .body(payload)
                .post("/api/patients")
                .then()
                .statusCode(200)
                .extract()
                .path("id"); // This captures the UUID generated by Patient Service

        // 2. Now use that UUID to check the Billing Service
        given()
                .header("Authorization", "Bearer " + token)
                .when()
                .get("/api/billing/account/" + extractedPatientId)
                .then()
                .log().ifValidationFails()
                .statusCode(200)
                .body("patientId", equalTo(extractedPatientId))
                .body("status", equalTo("ACTIVE"))
                .body("balance", equalTo(0)); // Comparing to 'int' as per your change
    }
}